### ISSUE TITLE
R9 docs pain points

### ISSUE THREAD

**Issue by olliw42** [olliw42/mLRS-docu#114]
it could be usefull to improve the R9 docs

- [x]  concerning indications when what went well or wrong, e.g. led blink patterns (motivated by https://github.com/olliw42/mLRS-docu/issues/111#issuecomment-1879045232)
- [x] usb adapters may give issues in using the bootloader flash method for receivers (motivated by https://github.com/olliw42/mLRS-docu/issues/111#issuecomment-1879045232)
- [x] picture of dip switch positions and theri effect (to better illustrate the text) (motivated by https://github.com/olliw42/mLRS-docu/issues/111#issuecomment-1879045232)
- [x] document that Python3 is needed as prerequiste (see https://discord.com/channels/1005096100572700794/1005268892437970945/1201816304793948240)
- [x] suggest that with mlrs-bridge configured to BT it is easy to also access the cli wirelessly, and no need for inverter (https://discord.com/channels/1005096100572700794/1005268892437970945/1201971234020266004 and ff)
